export declare const CloseCode: {
    gameNotFound: number;
    gameFull: number;
    badName: number;
    mainMenu: number;
    gameIdleExceeded: number;
    corruptedLoginData: number;
    gameMaxPlayersExceeded: number;
    gameDestroyUser: number;
    joinGameOutOfOrder: number;
    gameShuttingDown: number;
    readyBeforeReady: number;
    booted: number;
    gameErrorOnUserSocket: number;
    uuidNotFound: number;
    sessionNotFound: number;
    clusterFullCpu: number;
    clusterFullMem: number;
    noClustersAvailable: number;
    locked: number;
};